
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url:

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 'http://www.tylauncher.com'

# Google tracking id to track your visitors

google-tracking-id: "UA-73103396-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: luckytianyiyan
title: "Tyy Works"
description: "luckytianyiyan 的作品集."
keywords: "Tyy Works, luckytianyiyan, tyy, works, jekyll"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img:

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "luckytianyiyan 的作品集."
  # - text: "Where’s your will to be weird?"

me-img: "/img/luckytianyiyan.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "tyyworks"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/tylauncher-156x156.png"
    date: "2015年08月 - Today"
    description: "桌面应用 - TyLauncher 重构了 TyyAppManager, 并更名为 TyLauncher"
  - image: "/img/timeline/6-d_space-156x156.png"
    date: "2015年02月 - 2015年04月"
    description: "手游 - Six-dimensional Space(6-D Space、六维空间)"
  - image: "/img/timeline/tyy_app_manager-156x156.png"
    date: "2014年10月 - 2014年11月"
    description: "桌面应用 - TyyAppManager"
  - image: "/img/timeline/xiaoming_is_comming-156x156.png"
    date: "2014年05月 - 2014年11月"
    description: "手游 - 小明来了(XiaoMingIsComing)"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "luckytianyiyan@gmail.com"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/"
  # - title: "twitter"
  #   url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/luckytianyiyan"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  # Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING
  - CONTRIBUTORS

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
